# Generated by Django 4.2.6 on 2023-10-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_remove_progreso_file_progreso_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='archivo',
            field=models.FileField(default='', upload_to='archivos/', verbose_name='Archivo'),
        ),
    ]
